services:
  backend:
    container_name: hikelink
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.backend
    volumes:
      - media_volume:/app/media   
      - static_volume:/app/staticfiles
      - ./frontend/dist:/app/frontend/dist
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
      - ./frontend/dist:/app/frontend/dist 
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  
volumes:
  static_volume:
  media_volume: