services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: hikelink
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.backend
    volumes:
      - media_volume:/app/media   
      - static_volume:/app/staticfiles
      - ./frontend/dist:/app/frontend/dist
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      bash -c "./wait-for-it.sh db:5432 -- ./docker/prod/entrypoint.sh gunicorn config.wsgi:application --bind 0.0.0.0:8000"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
      - ./frontend/dist:/app/frontend/dist 
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  
volumes:
  pgdata:
  static_volume:
  media_volume: