version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    expose:
      - "8000"
    depends_on: []

  nginx:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume: