# Generated by Django 5.2.1 on 2025-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikelink_app', '0006_alter_route_difficulty_alter_route_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='difficulty',
            field=models.CharField(choices=[('Fácil', 'Facil'), ('Moderada', 'Moderada'), ('Difícil', 'Dificil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(choices=[('Strava', 'Strava'), ('Wikiloc', 'Wikiloc'), ('OutdoorActive', 'Outdooractive'), ('AllTrails', 'Alltrails'), ('Komoot', 'Komoot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Para-Todos', 'Para Todos'), ('Senderismo', 'Senderismo'), ('Ciclismo', 'Ciclismo'), ('Trail-Runnig', 'Trail Running'), ('Alpinismo', 'Alpinismo')], max_length=20),
        ),
    ]
