# Generated by Django 5.2.1 on 2025-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikelink_app', '0007_alter_route_description_alter_route_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Para-Todos', 'Para Todos'), ('Senderismo', 'Senderismo'), ('Ciclismo', 'Ciclismo'), ('Trail-Running', 'Trail Running'), ('Alpinismo', 'Alpinismo')], max_length=20),
        ),
    ]
