# Generated by Django 5.2.1 on 2025-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikelink_app', '0008_alter_route_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forothread',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
