# Generated by Django 5.2 on 2025-04-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikelink_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
