# Generated by Django 5.2 on 2025-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikelink_app', '0002_route_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
