# Generated by Django 5.2.1 on 2025-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikelink_app', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='difficulty',
            field=models.CharField(choices=[('Fácil', 'Facil'), ('Moderada', 'Moderada'), ('Difícil', 'Dificil')]),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(choices=[('Strava', 'Strava'), ('Wikiloc', 'Wikiloc'), ('OutdoorActive', 'Outdooractive'), ('AllTrails', 'Alltrails'), ('Komoot', 'Komoot')]),
        ),
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('Para-Todos', 'Para Todos'), ('Senderismo', 'Senderismo'), ('Ciclismo', 'Ciclismo'), ('Trail-Runnig', 'Trail Running'), ('Alpinismo', 'Alpinismo')]),
        ),
    ]
